FROM alpine:latest

COPY --from=mqtt-client_base /app/data/* /data/

COPY --from=mqtt-client_base /app/lib/* /lib/

COPY --from=mqtt-client_base /app/src/subscriber /app/

WORKDIR /app

ENTRYPOINT ["./subscriber", "-h", "broker"]