FROM alpine:latest

COPY . /app

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
 && apk --update --no-cache add build-base gcc libssl3 openssl-dev \
 && make -C /app \
 && rm -rf /var/cache/apk/*